version: '2'

services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Madrid
    - DELUGE_LOGLEVEL=error
    volumes:
    - /nfsDeluge:/config
    - /peliculas:/peliculas
    - /series:/series
    restart: unless-stopped
